### ISSUE TITLE
Allow for package release notation

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/nuget-chocolatey#11]
***WARNING*** : DO NOT USE this now. This will be introduced when the time is right. This will not work anywhere. 

We've long needed a better way to approach package release versions. Right now we have [package fix version notation](https://chocolatey.org/docs/create-packages#package-fix-version-notation) as a way to cover changes. However we've introduced this as a dark feature in Chocolatey v0.10.5 that will eventually be introduced that changes packages from NV (Name / Version) to the NVR (Name / Version / Release - we may eventually have architecture there as well) format. In short `<version>1.0.0</version>` represents `1.0.0_0` where 0 is the package release version (`name.1.0.0.nupkg`). `<version>1.0.0_2</version>` represents version 1.0.0, package release 2 (`name.1.0.0_2.nupkg`). It's a dark feature because we are still determining design and determining how to build out the infrastructure to work with this before introducing it. Nothing supports it as of yet, and it is an incompatible change for sources if used. It is a necessary one, but an incompatible change for packages that use it. If a package never uses package release version notation, that package would still be compatible on sources as `<version>1.0.0</version>` will still produce `name.1.0.0.nupkg`. 

A couple of additional points:

* This will only be seen when someone is fixing a package release without changing the underlying software (and its version).
* This makes package release a first class citizen, which is necessary and the only reason it was implemented.
* The release version notation is strictly just a numerical value. So `0`, `1`, `100` (heaven forbid), but never `release1`, `next`, etc.
* `1.0` == `1.0.0` == `1.0.0.0` == `1.0.0.0_0`
* `1.0.0` < `1.0.0_1` < `1.0.0_20` < `1.0.1-beta` < `1.0.1`
* For compatibility sake, when there isn't a specific release notation, the version shown as a string or normalize string will show as that number (e.g. it will show as `1.0.0`). When there is package release notation (`1.0.0_2`), it will show in the normalized string (`1.0.0.0_2`). This is near exact in how versioning works with the SemVer prerelease notation.

Scenarios for how a package repository API behaves. Let's say we have v1.0.0 and v1.0.0_2.

* request latest - you get `1.0.0_2`
* You request a specific version with release notation - you get that (e.g. request `1.0.0_0`, you get `1.0.0`)
* You request a specific version - you get the latest package release of that (e.g. request `1.0.0`, you get `1.0.0_2`) - this could be trickier to implement.

## DO NOT USE THIS YET
If anyone uses it right now, they will see it doesn't work. We plan to introduce this in the latter half of 2017 (maybe early 2018) when we have more systems able to work with it. That way all systems are as close to compatible when it is introduced.

## More Detail
For proper package release versioning, which allows for a NVR format
(Name Version Release) as part of the packaging, add
PackageReleaseVersion to SemanticVersion. This allows fixing a package
without having to up the version of the package version in a way that
could be confusing for others.

Previously the way to handle package fix version notation was done in a
way that supported passing `YYYYMMDD` in the fourth version segment.
However that has proved to be a hack at best as the 4th segment could
be used for the version of the package or a versioning scheme from a
package could technically use the fourth segment with a date notation.
While it is rare, it has been seen before on non-Windows platforms and
could be seen in Windows packaging at some point.

Provide the ability to create package versions with `_#` (e.g.
`1.0.0_1`) to signify a revision to the package itself without changing
the version of the package itself.

**Comment by apxltd** [comment]
Have you considered using SemVer v2 instead to manage this instead? From a quick scan of your code, it doesn't seem like there's support for it, but perhaps you should consider it b/c NuGet is shifting towards that too...

From my understanding of the requirements, I think the existing "+buildMetadata" prefix with a numeric-only constraint could be used for this same purpose; some ProGet users are doing this in the same manner. 

Anyway I created a placeholder issue here - https://inedo.myjetbrains.com/youtrack/issue/PG-1066

**Comment by ferventcoder** [comment]
> Have you considered using SemVer v2 instead to manage this instead? From a quick scan of your code, it doesn't seem like there's support for it, but perhaps you should consider it b/c NuGet is shifting towards that too...

We'll be supporting SemVer 2 as well.

**Comment by ferventcoder** [comment]
> From my understanding of the requirements, I think the existing "+buildMetadata" prefix with a numeric-only constraint could be used for this same purpose; some ProGet users are doing this in the same manner.

I'd be interested to know what they are doing.

For us we will be making other necessary changes as we continue to build out things specific to Chocolatey, however most are going to be pass through and transparent to the repository. This change is a known incompatibility that is likely to affect all repository vendors.

There are some specific pieces of the NuGet implementation of SemVer2's `+` that we'd need to know:

* Can it support `1.0.0.0+1` or is it strictly applied at 3 digits?
* Can it be limited to use based on a number? Locked down? Should it be? 
* What if software vendors opt-in to `+` notation? How does that get separated from the package release version?

I'm sure I have other relevant questions.

**Comment by apxltd** [comment]
I don't know off-hand, there is some giant GitHub issue/wiki or something that shows how they plan to support it... but I can't imagine they will ever support multiple package versions with different build metadata. So, how they support it, shouldn't really matter to chocolatey I think.

But this is a good idea for what you're doing -- presumably the only thing that's different inside a "versioned" package version is the installation script (arguably the "packaging"), not the contents. So it makes sense to me.

My advice: drop support for 4-part versions and move towards Semver2.  This way you're using a well-known standard instead of the bizarre, NuGet-inherited 4-part scheme.  It's worth noting, the NuGet team decided to break compatibility for this as well... and I think only a handful of popular packages were impacted.  And they have a much wider userbase. I would imagine, there are only a handful of packages you'd need to worry about, if that.

As to the questions, I can tell you what we did for Universal Packages. The SemVer2 specs leave it up to the implementer to decide what to do with build metadata, but it's very clear that they intend "1.0.0+1 and 1.0.0+2" to semantically be the same version, but with different "packaging" so to say.

So, we choose to allow multiple packages with different build metadatas. If you ask for a package without specifying metadata, we return the "greatest" version, which is a simply "if numeric, sort numericaly" comparer. I.e. +5 < +1000 < +abc < +oneThousand

If you ask for a  package with specific metadata, that specific package (or 404) is returned. Basically it's a little difficult to request a specific metadata package. 

As far as I can tell, this will accomplish what you're looking for  without breaking things by moving towards a _ notation...

**Comment by ferventcoder** [comment]
> My advice: drop support for 4-part versions and move towards Semver2. This way you're using a well-known standard instead of the bizarre, NuGet-inherited 4-part scheme. It's worth noting, the NuGet team decided to break compatibility for this as well... and I think only a handful of popular packages were impacted. And they have a much wider userbase. I would imagine, there are only a handful of packages you'd need to worry about, if that.

This isn't up to us. This is based on the existing software that is out there. Oracle has some products that actually have 5 or 6 segments

**Comment by apxltd** [comment]
Yeah, so what do you about that? A 5-segment version? Or a alpha-numeric version (v3.2b)?

At some point you have to make the actual package version number not match the vendor's version number, and then use additional metadata to capture the vendor's original version number and display it when needed. 

Hence why I'm suggesting drawing the line at SemVer2.

**Comment by maartenba** [comment]
+1 on @apapadimoulis

**Comment by ferventcoder** [comment]
There are hundreds of products in the Windows ecosystem that are 4 segments long - as that is what Microsoft used for years. We need a flexible solution that detaches away from software version, and that is what we've designed. 

There will be more changes as our needs are different, and that's fine. The two don't need to be exactly alike.

**Comment by apxltd** [comment]
Has this been implemented? We haven’t implemented it on PG, and we haven’t heard from any customers about it. I suppose ProGet already offers a for package versions (users can just republish on top of old versions), and it seems connector packages (i.e. from chocolatey.org) will always return the latest anyway.

**Comment by ferventcoder** [comment]
@apapadimoulis not across the board - we try to give more than six months notice. This will not be widely implemented until early 2018. That should give ProGet and others plenty of time to get out versions that are compatible with this change. Then, next year when a connector pulls down a package that has this notation, it won't error.

**Comment by ferventcoder** [comment]
@apapadimoulis The idea was to allow you not to hear from your customers in a negative way in a manner that is "fix this now" - at Chocolatey we are giving you a way early heads up. Once customers know about this, it is pretty intuitive that they will want to use it internally as well.

**Comment by apxltd** [comment]
Oh yes, now I remember! Thanks.

It appears to be a major change for us, so we will look to implement this in late Q4 or Q1 or something when we add full SemVer2 support for NuGet packages.

In the meantime, do you plan to create very specific documentation for your versioning scheme? Such as things like “1.09.0” < “1.8.0” (I think that’s a current behavior, used by a few packages… but we don’t support it now anyway).

**Comment by ferventcoder** [comment]
@apapadimoulis I've updated the very top post with very specific information since you first commented. To save you from scrolling back:

> A couple of additional points:
>* This will only be seen when someone is fixing a package release without changing the underlying software (and its version).
>* This makes package release a first class citizen, which is necessary and the only reason it was implemented.
>* The release version notation is strictly just a numerical value. So `0`, `1`, `100` (heaven forbid), but never `release1`, `next`, etc.
>* `1.0` == `1.0.0` == `1.0.0.0` == `1.0.0.0_0`
>* `1.0.0` < `1.0.0_1` < `1.0.0_20` < `1.0.1-beta` < `1.0.1`
>* For compatibility sake, when there isn't a specific release notation, the version shown as a string or normalize string will show as that number (e.g. it will show as `1.0.0`). When there is package release notation (`1.0.0_2`), it will show in the normalized string (`1.0.0.0_2`). This is near exact in how versioning works with the SemVer prerelease notation.
>
>Scenarios for how a package repository API behaves. Let's say we have v1.0.0 and v1.0.0_2.
>
>* request latest - you get 1.0.0_2
>* You request a specific version with release notation - you get that (e.g. request 1.0.0_0, you get 1.0.0)
>* You request a specific version - you get the latest package release of that (e.g. request 1.0.0, you get 1.0.0_2) - this could be trickier to implement.

**Comment by ferventcoder** [comment]
Just added this as well:
* `1.0.0` < `1.0.0_1` < `1.0.0_20` < `1.0.1-beta` < `1.0.1`

**Comment by apxltd** [comment]
Ah, i didn't see it. Thanks.

Is there a place in your docs where we can reference / link that describes the entire versioning scheme (not just this)? Maybe under choco package creation? Basically some specifications, so we know what's correct, what's a bug, and what we do/don't support.

**Comment by ferventcoder** [comment]
@apapadimoulis It's exactly the same as NuGet's versioning scheme for NuGet v2. We should probably set up our own documentation there.

**Comment by apxltd** [comment]
Yeah, I would recommend it; the v2 versioning scheme was undocumented and has a lot of quirks...  they made some breaking changes to it in 3.4, so it would be good for you to identify...
 * what is officially supported (documented)
 * what are "quirks" that you should not use because they are bad ideas
 * known bugs in current choco implementation / unsupported behavior

Here are two example quirks -- https://github.com/NuGet/Home/issues/2298#issuecomment-195595687
